// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: k5_proto/proto/mkp.proto

package protobufpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MkpSvcClient is the client API for MkpSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MkpSvcClient interface {
	// transfer token
	TransferErc721(ctx context.Context, in *TransferErc721Req, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TransferErc20(ctx context.Context, in *TransferErc20Req, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// auction
	CreateAuction(ctx context.Context, in *CreateAuctionReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateAuction(ctx context.Context, in *UpdateAuctionReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelAuction(ctx context.Context, in *CancelAuctionReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateBidding(ctx context.Context, in *CreateBiddingReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevealBidding(ctx context.Context, in *RevealBiddingReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// public auction
	PublicAuctionCreated(ctx context.Context, in *AuctionCreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PublicAuctionBid(ctx context.Context, in *AuctionBidReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PublicAuctionRefund(ctx context.Context, in *AuctionRefundReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PublicAuctionCancelled(ctx context.Context, in *AuctionCancelledReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PublicAuctionGrantReward(ctx context.Context, in *AuctionGrantRewardReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// blind auction
	BlindAuctionCreated(ctx context.Context, in *AuctionCreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BlindAuctionBid(ctx context.Context, in *AuctionBidReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BlindAuctionReveal(ctx context.Context, in *BlindAuctionRevealReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BlindAuctionRefund(ctx context.Context, in *AuctionRefundReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BlindAuctionCancelled(ctx context.Context, in *AuctionCancelledReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BlindAuctionGrantReward(ctx context.Context, in *AuctionGrantRewardReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// order
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// transaction
	CreateTransaction(ctx context.Context, in *CreateTransactionReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// nft
	CreateOrUpdateNft(ctx context.Context, in *CreateOrUpdateNftReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mkpSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewMkpSvcClient(cc grpc.ClientConnInterface) MkpSvcClient {
	return &mkpSvcClient{cc}
}

func (c *mkpSvcClient) TransferErc721(ctx context.Context, in *TransferErc721Req, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/TransferErc721", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) TransferErc20(ctx context.Context, in *TransferErc20Req, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/TransferErc20", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CreateAuction(ctx context.Context, in *CreateAuctionReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CreateAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) UpdateAuction(ctx context.Context, in *UpdateAuctionReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/UpdateAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CancelAuction(ctx context.Context, in *CancelAuctionReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CancelAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CreateBidding(ctx context.Context, in *CreateBiddingReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CreateBidding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) RevealBidding(ctx context.Context, in *RevealBiddingReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/RevealBidding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) PublicAuctionCreated(ctx context.Context, in *AuctionCreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/PublicAuctionCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) PublicAuctionBid(ctx context.Context, in *AuctionBidReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/PublicAuctionBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) PublicAuctionRefund(ctx context.Context, in *AuctionRefundReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/PublicAuctionRefund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) PublicAuctionCancelled(ctx context.Context, in *AuctionCancelledReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/PublicAuctionCancelled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) PublicAuctionGrantReward(ctx context.Context, in *AuctionGrantRewardReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/PublicAuctionGrantReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) BlindAuctionCreated(ctx context.Context, in *AuctionCreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/BlindAuctionCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) BlindAuctionBid(ctx context.Context, in *AuctionBidReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/BlindAuctionBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) BlindAuctionReveal(ctx context.Context, in *BlindAuctionRevealReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/BlindAuctionReveal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) BlindAuctionRefund(ctx context.Context, in *AuctionRefundReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/BlindAuctionRefund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) BlindAuctionCancelled(ctx context.Context, in *AuctionCancelledReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/BlindAuctionCancelled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) BlindAuctionGrantReward(ctx context.Context, in *AuctionGrantRewardReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/BlindAuctionGrantReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/UpdateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CreateTransaction(ctx context.Context, in *CreateTransactionReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mkpSvcClient) CreateOrUpdateNft(ctx context.Context, in *CreateOrUpdateNftReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.MkpSvc/CreateOrUpdateNft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MkpSvcServer is the server API for MkpSvc service.
// All implementations must embed UnimplementedMkpSvcServer
// for forward compatibility
type MkpSvcServer interface {
	// transfer token
	TransferErc721(context.Context, *TransferErc721Req) (*emptypb.Empty, error)
	TransferErc20(context.Context, *TransferErc20Req) (*emptypb.Empty, error)
	// auction
	CreateAuction(context.Context, *CreateAuctionReq) (*emptypb.Empty, error)
	UpdateAuction(context.Context, *UpdateAuctionReq) (*emptypb.Empty, error)
	CancelAuction(context.Context, *CancelAuctionReq) (*emptypb.Empty, error)
	CreateBidding(context.Context, *CreateBiddingReq) (*emptypb.Empty, error)
	RevealBidding(context.Context, *RevealBiddingReq) (*emptypb.Empty, error)
	// public auction
	PublicAuctionCreated(context.Context, *AuctionCreateReq) (*emptypb.Empty, error)
	PublicAuctionBid(context.Context, *AuctionBidReq) (*emptypb.Empty, error)
	PublicAuctionRefund(context.Context, *AuctionRefundReq) (*emptypb.Empty, error)
	PublicAuctionCancelled(context.Context, *AuctionCancelledReq) (*emptypb.Empty, error)
	PublicAuctionGrantReward(context.Context, *AuctionGrantRewardReq) (*emptypb.Empty, error)
	// blind auction
	BlindAuctionCreated(context.Context, *AuctionCreateReq) (*emptypb.Empty, error)
	BlindAuctionBid(context.Context, *AuctionBidReq) (*emptypb.Empty, error)
	BlindAuctionReveal(context.Context, *BlindAuctionRevealReq) (*emptypb.Empty, error)
	BlindAuctionRefund(context.Context, *AuctionRefundReq) (*emptypb.Empty, error)
	BlindAuctionCancelled(context.Context, *AuctionCancelledReq) (*emptypb.Empty, error)
	BlindAuctionGrantReward(context.Context, *AuctionGrantRewardReq) (*emptypb.Empty, error)
	// order
	CreateOrder(context.Context, *CreateOrderReq) (*emptypb.Empty, error)
	UpdateOrder(context.Context, *UpdateOrderReq) (*emptypb.Empty, error)
	CancelOrder(context.Context, *CancelOrderReq) (*emptypb.Empty, error)
	// transaction
	CreateTransaction(context.Context, *CreateTransactionReq) (*emptypb.Empty, error)
	// nft
	CreateOrUpdateNft(context.Context, *CreateOrUpdateNftReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedMkpSvcServer()
}

// UnimplementedMkpSvcServer must be embedded to have forward compatible implementations.
type UnimplementedMkpSvcServer struct {
}

func (UnimplementedMkpSvcServer) TransferErc721(context.Context, *TransferErc721Req) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferErc721 not implemented")
}
func (UnimplementedMkpSvcServer) TransferErc20(context.Context, *TransferErc20Req) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferErc20 not implemented")
}
func (UnimplementedMkpSvcServer) CreateAuction(context.Context, *CreateAuctionReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuction not implemented")
}
func (UnimplementedMkpSvcServer) UpdateAuction(context.Context, *UpdateAuctionReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAuction not implemented")
}
func (UnimplementedMkpSvcServer) CancelAuction(context.Context, *CancelAuctionReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAuction not implemented")
}
func (UnimplementedMkpSvcServer) CreateBidding(context.Context, *CreateBiddingReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBidding not implemented")
}
func (UnimplementedMkpSvcServer) RevealBidding(context.Context, *RevealBiddingReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealBidding not implemented")
}
func (UnimplementedMkpSvcServer) PublicAuctionCreated(context.Context, *AuctionCreateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicAuctionCreated not implemented")
}
func (UnimplementedMkpSvcServer) PublicAuctionBid(context.Context, *AuctionBidReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicAuctionBid not implemented")
}
func (UnimplementedMkpSvcServer) PublicAuctionRefund(context.Context, *AuctionRefundReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicAuctionRefund not implemented")
}
func (UnimplementedMkpSvcServer) PublicAuctionCancelled(context.Context, *AuctionCancelledReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicAuctionCancelled not implemented")
}
func (UnimplementedMkpSvcServer) PublicAuctionGrantReward(context.Context, *AuctionGrantRewardReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicAuctionGrantReward not implemented")
}
func (UnimplementedMkpSvcServer) BlindAuctionCreated(context.Context, *AuctionCreateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindAuctionCreated not implemented")
}
func (UnimplementedMkpSvcServer) BlindAuctionBid(context.Context, *AuctionBidReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindAuctionBid not implemented")
}
func (UnimplementedMkpSvcServer) BlindAuctionReveal(context.Context, *BlindAuctionRevealReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindAuctionReveal not implemented")
}
func (UnimplementedMkpSvcServer) BlindAuctionRefund(context.Context, *AuctionRefundReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindAuctionRefund not implemented")
}
func (UnimplementedMkpSvcServer) BlindAuctionCancelled(context.Context, *AuctionCancelledReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindAuctionCancelled not implemented")
}
func (UnimplementedMkpSvcServer) BlindAuctionGrantReward(context.Context, *AuctionGrantRewardReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindAuctionGrantReward not implemented")
}
func (UnimplementedMkpSvcServer) CreateOrder(context.Context, *CreateOrderReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedMkpSvcServer) UpdateOrder(context.Context, *UpdateOrderReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedMkpSvcServer) CancelOrder(context.Context, *CancelOrderReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMkpSvcServer) CreateTransaction(context.Context, *CreateTransactionReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedMkpSvcServer) CreateOrUpdateNft(context.Context, *CreateOrUpdateNftReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateNft not implemented")
}
func (UnimplementedMkpSvcServer) mustEmbedUnimplementedMkpSvcServer() {}

// UnsafeMkpSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MkpSvcServer will
// result in compilation errors.
type UnsafeMkpSvcServer interface {
	mustEmbedUnimplementedMkpSvcServer()
}

func RegisterMkpSvcServer(s grpc.ServiceRegistrar, srv MkpSvcServer) {
	s.RegisterService(&MkpSvc_ServiceDesc, srv)
}

func _MkpSvc_TransferErc721_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferErc721Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).TransferErc721(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/TransferErc721",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).TransferErc721(ctx, req.(*TransferErc721Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_TransferErc20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferErc20Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).TransferErc20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/TransferErc20",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).TransferErc20(ctx, req.(*TransferErc20Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CreateAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuctionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CreateAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CreateAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CreateAuction(ctx, req.(*CreateAuctionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_UpdateAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuctionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).UpdateAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/UpdateAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).UpdateAuction(ctx, req.(*UpdateAuctionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CancelAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAuctionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CancelAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CancelAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CancelAuction(ctx, req.(*CancelAuctionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CreateBidding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBiddingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CreateBidding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CreateBidding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CreateBidding(ctx, req.(*CreateBiddingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_RevealBidding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealBiddingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).RevealBidding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/RevealBidding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).RevealBidding(ctx, req.(*RevealBiddingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_PublicAuctionCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).PublicAuctionCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/PublicAuctionCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).PublicAuctionCreated(ctx, req.(*AuctionCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_PublicAuctionBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionBidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).PublicAuctionBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/PublicAuctionBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).PublicAuctionBid(ctx, req.(*AuctionBidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_PublicAuctionRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).PublicAuctionRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/PublicAuctionRefund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).PublicAuctionRefund(ctx, req.(*AuctionRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_PublicAuctionCancelled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionCancelledReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).PublicAuctionCancelled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/PublicAuctionCancelled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).PublicAuctionCancelled(ctx, req.(*AuctionCancelledReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_PublicAuctionGrantReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionGrantRewardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).PublicAuctionGrantReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/PublicAuctionGrantReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).PublicAuctionGrantReward(ctx, req.(*AuctionGrantRewardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_BlindAuctionCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).BlindAuctionCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/BlindAuctionCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).BlindAuctionCreated(ctx, req.(*AuctionCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_BlindAuctionBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionBidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).BlindAuctionBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/BlindAuctionBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).BlindAuctionBid(ctx, req.(*AuctionBidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_BlindAuctionReveal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlindAuctionRevealReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).BlindAuctionReveal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/BlindAuctionReveal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).BlindAuctionReveal(ctx, req.(*BlindAuctionRevealReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_BlindAuctionRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).BlindAuctionRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/BlindAuctionRefund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).BlindAuctionRefund(ctx, req.(*AuctionRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_BlindAuctionCancelled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionCancelledReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).BlindAuctionCancelled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/BlindAuctionCancelled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).BlindAuctionCancelled(ctx, req.(*AuctionCancelledReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_BlindAuctionGrantReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionGrantRewardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).BlindAuctionGrantReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/BlindAuctionGrantReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).BlindAuctionGrantReward(ctx, req.(*AuctionGrantRewardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/UpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).UpdateOrder(ctx, req.(*UpdateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CreateTransaction(ctx, req.(*CreateTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MkpSvc_CreateOrUpdateNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateNftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MkpSvcServer).CreateOrUpdateNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MkpSvc/CreateOrUpdateNft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MkpSvcServer).CreateOrUpdateNft(ctx, req.(*CreateOrUpdateNftReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MkpSvc_ServiceDesc is the grpc.ServiceDesc for MkpSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MkpSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.MkpSvc",
	HandlerType: (*MkpSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferErc721",
			Handler:    _MkpSvc_TransferErc721_Handler,
		},
		{
			MethodName: "TransferErc20",
			Handler:    _MkpSvc_TransferErc20_Handler,
		},
		{
			MethodName: "CreateAuction",
			Handler:    _MkpSvc_CreateAuction_Handler,
		},
		{
			MethodName: "UpdateAuction",
			Handler:    _MkpSvc_UpdateAuction_Handler,
		},
		{
			MethodName: "CancelAuction",
			Handler:    _MkpSvc_CancelAuction_Handler,
		},
		{
			MethodName: "CreateBidding",
			Handler:    _MkpSvc_CreateBidding_Handler,
		},
		{
			MethodName: "RevealBidding",
			Handler:    _MkpSvc_RevealBidding_Handler,
		},
		{
			MethodName: "PublicAuctionCreated",
			Handler:    _MkpSvc_PublicAuctionCreated_Handler,
		},
		{
			MethodName: "PublicAuctionBid",
			Handler:    _MkpSvc_PublicAuctionBid_Handler,
		},
		{
			MethodName: "PublicAuctionRefund",
			Handler:    _MkpSvc_PublicAuctionRefund_Handler,
		},
		{
			MethodName: "PublicAuctionCancelled",
			Handler:    _MkpSvc_PublicAuctionCancelled_Handler,
		},
		{
			MethodName: "PublicAuctionGrantReward",
			Handler:    _MkpSvc_PublicAuctionGrantReward_Handler,
		},
		{
			MethodName: "BlindAuctionCreated",
			Handler:    _MkpSvc_BlindAuctionCreated_Handler,
		},
		{
			MethodName: "BlindAuctionBid",
			Handler:    _MkpSvc_BlindAuctionBid_Handler,
		},
		{
			MethodName: "BlindAuctionReveal",
			Handler:    _MkpSvc_BlindAuctionReveal_Handler,
		},
		{
			MethodName: "BlindAuctionRefund",
			Handler:    _MkpSvc_BlindAuctionRefund_Handler,
		},
		{
			MethodName: "BlindAuctionCancelled",
			Handler:    _MkpSvc_BlindAuctionCancelled_Handler,
		},
		{
			MethodName: "BlindAuctionGrantReward",
			Handler:    _MkpSvc_BlindAuctionGrantReward_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _MkpSvc_CreateOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _MkpSvc_UpdateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MkpSvc_CancelOrder_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _MkpSvc_CreateTransaction_Handler,
		},
		{
			MethodName: "CreateOrUpdateNft",
			Handler:    _MkpSvc_CreateOrUpdateNft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k5_proto/proto/mkp.proto",
}
