// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: k5_proto/proto/token.proto

package protobufpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenSvcClient is the client API for TokenSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenSvcClient interface {
	TransferErc721(ctx context.Context, in *TransferErc721Req, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TransferErc20(ctx context.Context, in *TransferErc20Req, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tokenSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenSvcClient(cc grpc.ClientConnInterface) TokenSvcClient {
	return &tokenSvcClient{cc}
}

func (c *tokenSvcClient) TransferErc721(ctx context.Context, in *TransferErc721Req, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.TokenSvc/TransferErc721", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenSvcClient) TransferErc20(ctx context.Context, in *TransferErc20Req, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.TokenSvc/TransferErc20", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenSvcServer is the server API for TokenSvc service.
// All implementations must embed UnimplementedTokenSvcServer
// for forward compatibility
type TokenSvcServer interface {
	TransferErc721(context.Context, *TransferErc721Req) (*emptypb.Empty, error)
	TransferErc20(context.Context, *TransferErc20Req) (*emptypb.Empty, error)
	mustEmbedUnimplementedTokenSvcServer()
}

// UnimplementedTokenSvcServer must be embedded to have forward compatible implementations.
type UnimplementedTokenSvcServer struct {
}

func (UnimplementedTokenSvcServer) TransferErc721(context.Context, *TransferErc721Req) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferErc721 not implemented")
}
func (UnimplementedTokenSvcServer) TransferErc20(context.Context, *TransferErc20Req) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferErc20 not implemented")
}
func (UnimplementedTokenSvcServer) mustEmbedUnimplementedTokenSvcServer() {}

// UnsafeTokenSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenSvcServer will
// result in compilation errors.
type UnsafeTokenSvcServer interface {
	mustEmbedUnimplementedTokenSvcServer()
}

func RegisterTokenSvcServer(s grpc.ServiceRegistrar, srv TokenSvcServer) {
	s.RegisterService(&TokenSvc_ServiceDesc, srv)
}

func _TokenSvc_TransferErc721_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferErc721Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenSvcServer).TransferErc721(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.TokenSvc/TransferErc721",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenSvcServer).TransferErc721(ctx, req.(*TransferErc721Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenSvc_TransferErc20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferErc20Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenSvcServer).TransferErc20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.TokenSvc/TransferErc20",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenSvcServer).TransferErc20(ctx, req.(*TransferErc20Req))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenSvc_ServiceDesc is the grpc.ServiceDesc for TokenSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.TokenSvc",
	HandlerType: (*TokenSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferErc721",
			Handler:    _TokenSvc_TransferErc721_Handler,
		},
		{
			MethodName: "TransferErc20",
			Handler:    _TokenSvc_TransferErc20_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k5_proto/proto/token.proto",
}
